import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {join} from 'node:path';import {ROOT} from '../helpers/load.mjs';
test('LinkedIn Easy Apply excludes background search and retains required contact fields',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.route('https://www.linkedin.com/**',r=>r.fulfill({contentType:'text/html',body:'<label>Search<input id="search"></label><dialog open><h2>Apply to Example</h2><label>Email address*<select required><option>person@example.test</option></select></label><label>Phone country code*<select required><option>United States (+1)</option></select></label><label>Mobile phone number*<input type="tel" required></label></dialog>'}));await p.goto('https://www.linkedin.com/jobs/view/1/');await p.addScriptTag({path:join(ROOT,'extension/src/content/scrape.js')});const fields=await p.evaluate(()=>__formwork.scrape().schema.fields);assert.deepEqual(fields.map(f=>f.label),['Email address','Phone country code','Mobile phone number']);assert.ok(fields.every(f=>f.required));await p.locator('dialog').evaluate(e=>e.close());assert.deepEqual(await p.evaluate(()=>__formwork.scrape().schema.fields.map(f=>f.label)),['Search']);
});
test('LinkedIn saved resumes retain their question, required marker and exact selected file',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();
 await p.route('https://www.linkedin.com/**',r=>r.fulfill({contentType:'text/html',body:`<dialog open><h2>Apply to Example</h2><p>Resume*</p>${['backend.pdf','embedded.pdf'].map((name,i)=>`<div data-sdui-component="com.linkedin.sdui.generated.jobseeker.dsl.impl.uploadedDocument"><div role="radio" aria-label="${name}" onclick="this.querySelector('input').checked=true;this.setAttribute('aria-checked','true')"><div aria-label="${name}"><input type="radio" name="resume" id="r${i}"><label for="r${i}"></label></div></div></div>`).join('')}<fieldset><legend>Relocate?</legend><label><input type="radio" name="relocate">Yes</label><label><input type="radio" name="relocate">No</label></fieldset></dialog>`}));
 await p.goto('https://www.linkedin.com/jobs/view/1/');for(const file of ['scrape','fill'])await p.addScriptTag({path:join(ROOT,`extension/src/content/${file}.js`)});
 const result=await p.evaluate(async()=>{const s=__formwork.scrape();return {fields:s.schema.fields,report:await __formwork.fill({f0:'embedded.pdf'},s.schema,s.registry)};});
 assert.equal(result.fields[0].label,'Resume');assert.equal(result.fields[0].required,true);assert.deepEqual(result.fields[0].options,['backend.pdf','embedded.pdf']);assert.equal(result.fields[1].label,'Relocate?');assert.deepEqual(result.report.failed,[]);assert.equal(await p.locator('#r1').isChecked(),true);assert.equal(await p.locator('#r0').isChecked(),false);
 await p.locator('dialog > p').evaluate(e=>e.textContent='Resume');assert.equal(await p.evaluate(()=>__formwork.scrape().schema.fields[0].required),false);
});
test('LinkedIn required screening question comes from its own caption, not the application heading',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.route('https://www.linkedin.com/**',r=>r.fulfill({contentType:'text/html',body:`<dialog open><h2>Apply to Example</h2>${['Authorized to work?*','Relocate?'].map((q,i)=>`<div componentkey="easyApplyFieldFocus_${i}"><p>${q}</p><fieldset role="radiogroup">${['Yes','No'].map((v,j)=>`<div role="radio" aria-label="${q}"><input type="radio" name="q${i}" id="q${i}${j}"><label for="q${i}${j}">${v}</label></div>`).join('')}</fieldset></div>`).join('')}</dialog>`}));await p.goto('https://www.linkedin.com/jobs/view/1/');await p.addScriptTag({path:join(ROOT,'extension/src/content/scrape.js')});const fields=await p.evaluate(()=>__formwork.scrape().schema.fields);assert.deepEqual(fields.map(f=>[f.label,f.required,f.options]),[['Authorized to work?',true,['Yes','No']],['Relocate?',false,['Yes','No']]]);
});
test('controlled radio waits for asynchronous commit without clicking twice',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.setContent(`<fieldset><legend>Authorized?</legend><div role="radio" aria-label="Yes" aria-checked="false" onclick="window.clicks=(window.clicks||0)+1;this.querySelector('input').checked=true;setTimeout(()=>{this.setAttribute('aria-checked','true')},100)"><input type="radio" name="auth"><span>Yes</span></div></fieldset>`);for(const file of ['scrape','fill'])await p.addScriptTag({path:join(ROOT,`extension/src/content/${file}.js`)});const result=await p.evaluate(async()=>{const s=__formwork.scrape();return {report:await __formwork.fill({f0:'Yes'},s.schema,s.registry),clicks:window.clicks};});assert.deepEqual(result.report.failed,[]);assert.deepEqual(result.report.filled,['f0']);assert.equal(result.clicks,1);
});
test('controlled checkbox waits for asynchronous opt-out without toggling twice',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.setContent(`<div role="checkbox" aria-label="Follow employer" aria-checked="true" onclick="window.clicks=(window.clicks||0)+1;this.querySelector('input').checked=false;setTimeout(()=>this.setAttribute('aria-checked','false'),100)"><input type="checkbox" checked><span>Follow employer</span></div>`);for(const file of ['scrape','fill'])await p.addScriptTag({path:join(ROOT,`extension/src/content/${file}.js`)});const result=await p.evaluate(async()=>{const s=__formwork.scrape();return {report:await __formwork.fill({f0:'false'},s.schema,s.registry),clicks:window.clicks};});assert.deepEqual(result.report.failed,[]);assert.deepEqual(result.report.filled,['f0']);assert.equal(result.clicks,1);
});
