import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {join} from 'node:path';import {ROOT} from '../helpers/load.mjs';
for(const reject of [false,true])test(`Paylocity select requires a committed answer (${reject?'ignored':'accepted'})`,async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();
 await p.setContent(`<label>State<div class="pcty-input-select-full-container" aria-owns="state-list"><span class="input-select-input-single-value">CA</span><div class="pcty-input-select__input"><input id="state" aria-autocomplete="list"></div></div></label>`);
 await p.evaluate(reject=>{const input=document.querySelector('input');const close=()=>document.getElementById('state-list')?.remove();const open=()=>{if(document.getElementById('state-list'))return;const list=document.createElement('div');list.id='state-list';list.className='pcty-input-select__menu-list';for(const v of ['CA','NC']){const n=document.createElement('div');n.id='state-select-row-'+v;n.title=v;n.textContent=v;n.onclick=()=>{if(!reject){document.querySelector('.input-select-input-single-value').textContent=v;input.value='';close()}};list.append(n)}document.body.append(list)};input.onkeydown=e=>{if(e.key==='ArrowDown')open();if(e.key==='Escape')close()};},reject);
 for(const file of ['scrape.js','fill.js'])await p.addScriptTag({path:join(ROOT,'extension/src/content',file)});
 const r=await p.evaluate(async()=>{const s=await __formwork.scrapeFull();return {field:s.schema.fields[0],report:await __formwork.fill({f0:'NC'},s.schema,s.registry)}});
 assert.equal(r.field.label,'State');assert.deepEqual(r.field.options,['CA','NC']);assert.deepEqual(r.report.filled,reject?[]:['f0']);assert.equal(r.report.failed.length,reject?1:0);
});
test('Paylocity street suggestions allow retained free text',async t=>{const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.route('https://recruiting.paylocity.com/**',r=>r.fulfill({contentType:'text/html',body:'<label for="address">Address Line 1</label><input id="address" data-automation-id="public-site-address-address-1" role="combobox" aria-autocomplete="list" required>'}));await p.goto('https://recruiting.paylocity.com/test');for(const f of ['scrape.js','fill.js'])await p.addScriptTag({path:join(ROOT,'extension/src/content',f)});const r=await p.evaluate(async()=>{const s=__formwork.scrape();return {field:s.schema.fields[0],report:await __formwork.fill({f0:'114 Rosewood Lane'},s.schema,s.registry)}});assert.equal(r.field.type,'text');assert.deepEqual(r.report.filled,['f0']);});
test('Paylocity inline rejection is not reported as filled or inherited by adjacent fields',async t=>{
 const b=await chromium.launch();t.after(()=>b.close());const p=await b.newPage();await p.route('https://recruiting.paylocity.com/**',r=>r.fulfill({contentType:'text/html',body:'<div class="form-group form-error"><label>LinkedIn Profile URL<input id="url"></label><div class="type-footnote show">Must be a valid LinkedIn URL</div></div><div class="form-group"><label>First Name<input id="name"></label></div>'}));await p.goto('https://recruiting.paylocity.com/test');for(const f of ['scrape.js','fill.js'])await p.addScriptTag({path:join(ROOT,'extension/src/content',f)});const r=await p.evaluate(async()=>{const s=__formwork.scrape();return __formwork.fill({f0:'https://example.invalid/profile',f1:'Dana'},s.schema,s.registry)});assert.deepEqual(r.filled,['f1']);assert.equal(r.failed.length,1);
});
