// Generated by tools/build-humanizer.py; edit dashboard/humanize.py.
(function(root) {
  const rules = {
  "upstream": "https://github.com/blader/humanizer",
  "version": "3.0.0",
  "phrases": [
    [
      "§1",
      "not X but Y",
      "State the point directly instead of setting it against something nobody claimed.",
      false,
      [
        "\\bnot (?:only|just|merely|simply)\\b[^.!?]{1,90}?\\bbut\\b",
        "\\b(?:it'?s not|not (?:only|just|merely|simply))\\b[^.!?]{1,80}?[,;:—–]\\s*it'?s\\b",
        "\\bisn'?t (?:just|only|merely|simply|about)\\b",
        "\\bthis (?:does not|doesn'?t) mean\\b[^.!?]{0,60}[.!?]\\s*it means\\b"
      ]
    ],
    [
      "§2",
      "one-line closer",
      "Cut any closing line that only restates the paragraph above it.",
      false,
      [
        "\\bthat'?s the real (?:win|point|story)\\b",
        "\\blet that sink in\\b",
        "\\bread that again\\b",
        "\\bthat'?s what (?:matters|counts)\\b"
      ]
    ],
    [
      "§3",
      "sayings that sound deep",
      "Replace any 'at its core' / 'what really matters' phrasing with the specific claim.",
      false,
      [
        "\\bthe real question is\\b",
        "\\bat its core\\b",
        "\\bwhat really matters\\b",
        "\\bthe heart of the matter\\b",
        "\\bthe deeper (?:issue|question)\\b",
        "\\bthe (?:language|currency|architecture) of\\b"
      ]
    ],
    [
      "§4",
      "staged run-up",
      "Open on a fact about the work, not on an announcement that you are about to say something.",
      false,
      [
        "\\bi am writing to (?:apply|express|submit)\\b",
        "\\blet'?s (?:dive|explore|break this down)\\b",
        "\\bhere'?s (?:the thing|what you need to know)\\b",
        "\\bthe thing is\\b",
        "\\blet'?s be honest\\b",
        "\\breal talk\\b",
        "^\\s*(?:look|honestly)[,?]"
      ]
    ],
    [
      "§5",
      "arguing with no one",
      "Remove the defence against an objection the reader has not made.",
      false,
      [
        "\\bthis isn'?t (?:mainly )?about\\b",
        "\\bi'?m not saying\\b",
        "\\bdon'?t get me wrong\\b",
        "\\bto be clear\\b",
        "\\bsome might say\\b",
        "\\byou might think\\b[^.!?]{1,60}\\bbut\\b"
      ]
    ],
    [
      "§9",
      "stacked qualifiers",
      "Say it once, plainly, instead of hedging the same claim twice.",
      true,
      [
        "\\bcould potentially\\b",
        "\\bmight arguably\\b",
        "\\bit'?s also possible\\b",
        "\\bin some cases it may\\b",
        "\\bto be fair\\b"
      ]
    ],
    [
      "§10",
      "hyphenated pairs",
      "Drop the stock hyphenated pairs: cross-functional, data-driven, end-to-end.",
      true,
      [
        "\\b(?:cross-functional|client-facing|data-driven|decision-making|high-quality|real-time|long-term|end-to-end|results-driven|detail-oriented)\\b"
      ]
    ],
    [
      "§12",
      "stock AI words",
      "Cut the stock vocabulary: delve, leverage, robust, passionate, align with, showcase.",
      true,
      [
        "\\b(?:delve|deep dive|bolstered|garner|interplay|intricacies|tapestry|testament|underscores?|showcas(?:e|es|ing)|meticulous(?:ly)?|pivotal|vibrant|crucial|foster(?:s|ing)?|leverag(?:e|es|ing)|align with|passionate about|thrilled|excited to bring)\\b"
      ]
    ],
    [
      "§15",
      "shallow -ing riders",
      "Cut the trailing '-ing' clause that adds importance rather than information.",
      true,
      [
        ",\\s+(?:highlighting|underscoring|emphasizing|ensuring|reflecting|symbolizing|contributing to|cultivating|fostering|encompassing|showcasing)\\b"
      ]
    ],
    [
      "§16",
      "sales language",
      "Describe the work; do not advertise it.",
      true,
      [
        "\\b(?:boasts|renowned|groundbreaking|cutting-edge|best-in-class|world-class|diverse array|proven track record|uniquely positioned)\\b"
      ]
    ],
    [
      "§18",
      "avoiding is and has",
      "Use 'is' and 'has' rather than 'serves as' or 'stands as'.",
      true,
      [
        "\\b(?:serves as|stands as|functions as|operates as)\\b"
      ]
    ],
    [
      "§22",
      "chatbot residue",
      "Remove every line addressed to whoever asked for the letter.",
      false,
      [
        "\\bi hope this helps\\b",
        "\\b(?:of course|certainly|great question)[!.]",
        "\\byou'?re absolutely right\\b",
        "\\b(?:would you like|want me to|should i continue)\\b",
        "\\blet me know if\\b",
        "^\\s*here(?:'?s| is) (?:a|the|your)\\b",
        "\\bas an ai\\b"
      ]
    ],
    [
      "§23",
      "knowledge-limit disclaimer",
      "Remove anything about what you do or do not know about the company.",
      false,
      [
        "\\bas of my (?:last )?(?:training|knowledge)\\b",
        "\\bbased on (?:the )?available information\\b",
        "\\bwhile specific details\\b",
        "\\bnot (?:publicly available|widely documented)\\b",
        "\\bit is believed that\\b"
      ]
    ],
    [
      "§25",
      "revision residue",
      "Describe the work itself; remove commentary about revising this draft.",
      false,
      [
        "\\b(?:in this revised version|the revised (?:letter|draft)|i have (?:revised|rewritten) (?:the|your)|compared (?:with|to) the previous (?:draft|version))\\b"
      ]
    ]
  ],
  "simple": [
    [
      "!",
      "unfilled placeholder",
      "Remove every bracketed blank; write the real detail or leave the sentence out.",
      "\\[[^\\]\\n]{2,40}\\]|\\{\\{[^}\\n]{1,40}\\}\\}|\\bXXX+\\b"
    ],
    [
      "!",
      "salutation or sign-off",
      "Write the letter body only — no 'Dear…' line and no sign-off.",
      "^\\s*(?:dear\\b[^\\n]{0,60}|to whom it may concern\\b[^\\n]{0,20})$|^\\s*(?:sincerely|best regards|kind regards|warm regards|yours (?:truly|faithfully))\\b[,.]?\\s*$"
    ],
    [
      "§19",
      "markdown formatting",
      "Plain prose only: no asterisks, headings, bullets or emoji.",
      "\\*\\*[^*\\n]+\\*\\*|^\\s{0,3}#{1,6}\\s|^\\s{0,3}[-*+]\\s+|[\\u{1F300}-\\u{1FAFF}→]"
    ]
  ],
  "prompt": "Write the way a person writes: plain sentences of uneven length, no dashes, no bullet points or bold, and no list of exactly three things unless there are three. Open with something you did, never with an announcement that you are applying. Do not end on a line that restates the paragraph above it. Avoid delve, leverage, robust, passionate, showcase, align with, and testament. Name who did the work; retain passive voice when the actor is unknown or irrelevant. Support significance, connections and attributed opinions with the supplied evidence. Do not inflate importance or borrow unnamed experts' authority. Avoid repeating a heading in the next sentence or talking about earlier drafts. Preserve the meaning of every claim, including rankings, qualifications, numbers, names and dates. Follow the writer's own samples where their deliberate style differs from this checklist."
};
  if (typeof module === "object" && module.exports) module.exports = rules;
  else (root.__formwork = root.__formwork || {}).humanizerRules = rules;
})(globalThis);
