"""Export the dashboard's style rules for the extension; --check detects drift."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from dashboard import humanize

data = {
    "upstream": "https://github.com/blader/humanizer",
    "version": humanize.UPSTREAM_VERSION,
    "phrases": humanize._PHRASES,
    "simple": [
        ["!", "unfilled placeholder", "Remove every bracketed blank; write the real detail or leave the sentence out.", humanize._PLACEHOLDER.pattern],
        ["!", "salutation or sign-off", "Write the letter body only — no 'Dear…' line and no sign-off.", humanize._SALUTATION.pattern],
        ["§19", "markdown formatting", "Plain prose only: no asterisks, headings, bullets or emoji.", humanize._MARKUP.pattern.replace(r"\U0001F300", r"\u{1F300}").replace(r"\U0001FAFF", r"\u{1FAFF}")],
    ],
    "prompt": humanize.PROMPT_RULES,
}
target = ROOT / "extension/src/lib/humanizer-rules.js"
output = '// Generated by tools/build-humanizer.py; edit dashboard/humanize.py.\n' + '''(function(root) {
  const rules = DATA;
  if (typeof module === "object" && module.exports) module.exports = rules;
  else (root.__formwork = root.__formwork || {}).humanizerRules = rules;
})(globalThis);
'''.replace("DATA", json.dumps(data, ensure_ascii=False, indent=2))
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
if parser.parse_args().check:
    if not target.exists() or target.read_text() != output:
        sys.exit("Humanizer rules are stale: run python3 tools/build-humanizer.py")
else:
    target.write_text(output)
